### ISSUE TITLE
FEATURE: Create Wiki and Update Docs

### ISSUE THREAD

**Issue by pacollins** [pacollins/hugo-future-imperfect-slim#85]
# Feature Request

## Is your feature request related to a problem?

In an effort to increase theme usability, we should update documentation and flesh out the wiki for new users.

## Tasks

- [X] Update [`theme.toml`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/theme.toml)
- [x] Update [`README.md`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/README.md)
- [X] Confirm [`LICENSE.md`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/LICENSE.md)
- [x] Remove [`stale.yml`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/stale.yml)
- [x] Update [`PULL_REQUEST_TEMPLATE.md`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
- [x] Update [`CONTRIBUTING.md`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CONTRIBUTING.md)
- [x] Update [`CODE_OF_CONDUCT.md`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/CODE_OF_CONDUCT.md)
- [ ] Update [`bug_report.md`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
- [ ] Update [`PULL_REQUEST_TEMPLATE.md`](https://github.com/pacollins/hugo-future-imperfect-slim/blob/master/.github/ISSUE_TEMPLATE/feature_request.md)
- [ ] Add additional templates as needed

**Comment by Jubijub** [comment]
hey Patrick,

I'd love to contribute to this, especially on how to use the theme. the example website is not necessarily aligned with the best practices (cf the recent commit on images vs featured).
What is the best format to contribute ?

**Comment by pacollins** [comment]
The best way with the Wiki is to just jump in. You can either type it online or you can actually clone it.

My vision for the wiki is essentially 1 page for each file (as needed). So if you wanted to start, you could develop the `config.toml` page that briefly states and shows (with pics) what each setting does.

**Comment by pacollins** [comment]
[`config.toml` is now live in the wiki.](https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml)
